jobs:
  build-and-test:
    docker:
      - image: cimg/ruby:3.1.1
    steps:
      - checkout
      - ruby/install-gems:
          pkg-manager: bundle install
      - run:
          name: Run tests
          command: rspec
